# Generated by Django 4.2.20 on 2025-04-25 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvguide', '0001_initial'),
    ]

    operations = [
    ]
