# Generated by Django 4.2.20 on 2025-04-25 11:09

from django.db import migrations
# Import datetime explicitly if needed for comparison/manipulation, though not strictly necessary for seeding here
# from datetime import datetime
# Import the static data
from tvguide.data import CHANNELS, PROGRAMS

def seed_data(apps, schema_editor):
    """
    Populates the database with initial Channel and Program data.
    """
    Channel = apps.get_model('tvguide', 'Channel')
    Program = apps.get_model('tvguide', 'Program')
    db_alias = schema_editor.connection.alias

    # Keep track of created channels to link programs
    created_channels = {}

    # Seed Channels
    print("\nSeeding Channels...") # Add print statement for visibility
    channels_to_create = []
    for channel_data in CHANNELS:
        # Check if channel already exists by name to avoid duplicates if migration runs again
        # Although typically data migrations run once. Using get_or_create is safer.
        channel, created = Channel.objects.using(db_alias).get_or_create(
            name=channel_data['name'],
            defaults={'country': channel_data['country']}
        )
        if created:
            print(f"  Created Channel: {channel.name}")
        else:
            print(f"  Channel already exists: {channel.name}")
        # Store the channel instance using the original ID from the static data for easy lookup
        created_channels[channel_data['id']] = channel

    # Seed Programs
    print("Seeding Programs...")
    programs_to_create = []
    for program_data in PROGRAMS:
        # Find the corresponding Channel object using the stored mapping
        channel_instance = created_channels.get(program_data['channel_id'])
        if channel_instance:
            # Check if program already exists (e.g., by title and channel)
            program, created = Program.objects.using(db_alias).get_or_create(
                title=program_data['title'],
                channel=channel_instance,
                defaults={
                    'description': program_data['description'],
                    'start_time': program_data['start_time'],
                    'end_time': program_data['end_time'],
                }
            )
            if created:
                 print(f"  Created Program: {program.title} on {channel_instance.name}")
            else:
                 print(f"  Program already exists: {program.title} on {channel_instance.name}")

        else:
            print(f"  Warning: Channel ID {program_data['channel_id']} not found for program '{program_data['title']}'. Skipping.")

    # Note: bulk_create is faster but doesn't call save() methods or signals.
    # Using get_or_create is safer for potentially re-runnable migrations.

class Migration(migrations.Migration):

    dependencies = [
        # Correct dependency: should depend on the migration that created the models
        ('tvguide', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_data),
    ]
