# Generated by Django 4.2.20 on 2025-04-25 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvguide', '0002_seed_initial_data'),
        ('tvguide', '0003_seed_initial_data'),
    ]

    operations = [
    ]
